---
# tasks file for yudus.ludus_tpot_server
- name: Mettre à jour les paquets
  apt:
    update_cache: yes
    upgrade: dist

- name: Installer les dépendances nécessaires
  apt:
    name:
      - curl
      - git
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Télécharger le script d'installation de T-Pot
  get_url:
    url: https://github.com/telekom-security/tpotce/raw/master/iso/installer/install.sh
    dest: /opt/tpot-install.sh
    mode: '0755'

- name: Exécuter le script d'installation T-Pot (⚠️ interactivité)
  command: bash /opt/tpot-install.sh
  args:
    creates: /opt/tpot/  # évite de relancer si déjà fait

