---
- name: Installer dépendances système
  apt:
    name:
      - git
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Cloner le dépôt T-Pot CE
  git:
    repo: https://github.com/telekom-security/tpotce.git
    dest: /opt/tpotce
    version: master
    force: yes

- name: Copier le fichier d'installation modifié (non interactif)
  copy:
    src: install.sh
    dest: /opt/tpotce/iso/installer/install.sh
    mode: '0755'

- name: Exécuter le script d'installation T-Pot custom
  command: bash /opt/tpotce/iso/installer/install.sh
  args:
    creates: /opt/tpot

